apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddit-clone-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - reddit-clone.example.com
      secretName: reddit-clone-tls
  rules:
    - host: reddit-clone.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reddit-clone-service
                port:
                  number: 80
