apiVersion: v1
kind: Namespace
metadata:
  name: reddit-clone-dev
  labels:
    app: reddit-clone
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: reddit-clone-prod
  labels:
    app: reddit-clone
    environment: prod
